### ISSUE TITLE
Meshinfo stops runnig

### ISSUE THREAD

**Issue by memo-567** [MeshAddicts/meshinfo#47]
From time to time, without any (for me) apparent reason, meshinfo crashes.

There appear to be several errors. The log file is attached.

[meshinfo-1  ERROR Exceptio.txt](https://github.com/user-attachments/files/16244608/meshinfo-1.ERROR.Exceptio.txt)

**Comment by kevinelliott** [comment]
Fixed in https://github.com/MeshAddicts/meshinfo/commit/418f9cda189e828be2557d14ef906fc73a11436a.

@memo-567 give it a shot with v0.0.243. Let me know if this helps.

**Comment by memo-567** [comment]
@kevinelliott  No, unfortunately not. Still the same error  ¯\\\_(ツ)_/¯

**Comment by memo-567** [comment]
Meshinfo always stops at the same point (see log)

[20240715-1224.txt](https://github.com/user-attachments/files/16247229/20240715-1224.txt)

**Comment by kevinelliott** [comment]
Alright @memo-567 try giving v0.0.244 a shot. That specific error should be resolved.

**Comment by memo-567** [comment]
@kevinelliott  No, unfortunately not either. I have now installed meshinfo in parallel on an HP thin client. It seems to be running error-free there. I'll continue testing there and shut down the Raspberry first.

Thank you for your hard work searching. Perhaps this is just a device-specific problem.
